import { loadRepoEnv } from "./env";
import type { ProjectKind } from "./projects";

/**
 * OmniRoute client config. Every value is read server-side only — the gateway
 * key is never sent to, or bundled for, the browser.
 */

export type OmniRouteConfig = {
  baseUrl: string;
  chatPath: string;
  apiKey: string;
  model: string;
};

export type PriorFile = {
  path: string;
  contents: string;
};

const DEFAULT_BASE_URL = "http://127.0.0.1:20128/v1";
const DEFAULT_CHAT_PATH = "/chat/completions";
const DEFAULT_MODEL = "auto/coding";

/** Values shipped in `.env.example` that must not be treated as real credentials. */
const PLACEHOLDER_PREFIXES = ["change-me", "changeme", "your-", "xxx", "todo"];

export function isPlaceholderSecret(value: string): boolean {
  const lowered = value.trim().toLowerCase();
  if (!lowered) return true;
  return PLACEHOLDER_PREFIXES.some((prefix) => lowered.startsWith(prefix));
}

export function readConfig(): OmniRouteConfig {
  loadRepoEnv();

  return {
    baseUrl: (process.env.OMNIROUTE_BASE_URL?.trim() || DEFAULT_BASE_URL).replace(/\/+$/, ""),
    chatPath: process.env.OMNIROUTE_CHAT_PATH?.trim() || DEFAULT_CHAT_PATH,
    apiKey: process.env.OMNIROUTE_API_KEY?.trim() || "",
    model: process.env.OMNIROUTE_MODEL?.trim() || DEFAULT_MODEL,
  };
}

export function chatCompletionsUrl(config: OmniRouteConfig): string {
  const path = config.chatPath.startsWith("/") ? config.chatPath : `/${config.chatPath}`;
  return `${config.baseUrl}${path}`;
}

/**
 * The output contract. Studio renders whatever the model emits inside a
 * sandboxed iframe with no network access, so generated apps must be
 * dependency-free and self-contained.
 */
export const SYSTEM_PROMPT = `You are Studio, the build agent inside Olympus. The user describes a web app in plain language and you return complete, runnable source files.

Output rules — follow them exactly:
- Reply with one or more file blocks and nothing else. No prose, no preamble, no explanation, no markdown fences.
- Wrap every file exactly like this:
<file path="index.html">
...file contents...
</file>
- Always include index.html. It is the entry point and is rendered live in a sandboxed iframe.
- Rewrite each file in full on every turn. Never emit patches, diffs, or partial edits.
- Keep the file set small: index.html plus optional styles.css and app.js.

Runtime rules — the preview has no network access and no build step:
- Vanilla HTML, CSS, and JavaScript only.
- No CDN script or stylesheet tags, no npm imports, no external fonts, no fetch/XHR to third parties.
- Inline CSS in a <style> tag or in styles.css; inline JS in a <script> tag or in app.js.
- Keep all state in memory. Use localStorage only if the user explicitly asks for persistence.

Design rules:
- Semantic HTML, responsive layout, and visible focus states.
- Make it look deliberate: real spacing, a coherent colour palette, sensible typography.
- Ship something that runs the moment it renders — no placeholder TODOs.`;

/**
 * The website contract: a React project, not a self-contained page.
 *
 * The model writes the SITE, the packaging step writes the PROJECT. That split is
 * deliberate and it is the same rule as everywhere else in this repo — scripts own
 * what must be deterministic. `package.json`, `vite.config.ts`, `tsconfig.json`,
 * `index.html` and `src/main.tsx` are generated by
 * `.archon/workflows/app/greenfield/scripts/package.py` with pinned, known-good
 * dependency versions, because a model-chosen version range turns "the site
 * builds" into a coin flip and a failed `npm install` into a build that reports
 * nothing useful. The model's job is the part that needs judgement: the component
 * and its styles.
 *
 * What the model must still get right is the contract with that scaffold: a
 * default-exported component in `src/App.tsx`, styles it can import, and no
 * dependency it did not declare — because there is nowhere to declare one.
 */
export const WEBSITE_SYSTEM_PROMPT = `You are Studio, the build agent inside Olympus. The user describes a website in plain language and you return the React components and styles that implement it.

Output rules — follow them exactly:
- Reply with one or more file blocks and nothing else. No prose, no preamble, no explanation, no markdown fences.
- Wrap every file exactly like this:
<file path="src/App.tsx">
...file contents...
</file>
- Always include src/App.tsx. It must \`export default\` a React component and it is the site's entry point.
- Put styles in src/index.css (imported by App.tsx) or in inline style objects. Extra components go in src/components/<Name>.tsx.
- Rewrite each file in full on every turn. Never emit patches, diffs, or partial edits.

THE PROJECT AROUND YOUR FILES IS ALREADY DECIDED. Do not emit package.json, vite.config.ts, tsconfig.json, index.html, or src/main.tsx — they are generated with pinned versions and your files are dropped into them. Writing them changes nothing except your own output size.

Runtime rules:
- React 19 with TypeScript and JSX. Use function components and hooks.
- NO DEPENDENCIES. There is no package to add one to: no npm imports, no CSS frameworks, no icon packs, no charting libraries, no animation libraries. React and the browser are what you have.
- No external fonts and no CDN tags. Use system font stacks.
- No network calls at runtime. If the site needs data, ship it as a constant in the source.
- Images: inline SVG or CSS gradients. Never a remote URL.

Design rules:
- This is a real website, not a demo page: a header, a main content area, and a footer are the floor, not the goal.
- Semantic HTML (header/nav/main/section/footer/h1–h3), responsive without a grid library, and visible focus states.
- Make it look deliberate: real spacing scale, one coherent colour palette, typographic hierarchy, sensible max-width for text.
- Mobile-first: it has to read well at 360px and look composed at 1440px.
- Ship a finished site — no placeholder lorem ipsum, no TODO comments, no "coming soon" sections.`;

/** The prompt for a kind, so no caller has to decide this twice. */
export function systemPromptFor(kind: ProjectKind = "app"): string {
  return kind === "website" ? WEBSITE_SYSTEM_PROMPT : SYSTEM_PROMPT;
}

/**
 * The turn's messages.
 *
 * `kind` selects the contract, and it is required rather than defaulted: a caller
 * that forgot to pass it would silently generate an app for a website, and the
 * failure that produces (JSX written as a plain script tag, or a self-contained
 * page where a component was asked for) reads like a model quality problem rather
 * than the missing argument it is. `systemPromptFor` still defaults for tests, but
 * every real call site states what it is building.
 */
export function buildMessages(
  prompt: string,
  priorFiles: PriorFile[],
  kind: ProjectKind,
): Array<{ role: "system" | "user"; content: string }> {
  const messages: Array<{ role: "system" | "user"; content: string }> = [
    { role: "system", content: systemPromptFor(kind) },
  ];

  if (priorFiles.length > 0) {
    // What the previous files are called differs by kind, and the word matters:
    // a website's files are the site, and telling the model it is looking at "the
    // app" nudges it back toward the app contract.
    const label = kind === "website" ? "site" : "app";
    const rendered = priorFiles
      .map((file) => `<file path="${file.path}">\n${file.contents}\n</file>`)
      .join("\n\n");

    messages.push({
      role: "user",
      content: `Current version of the ${label}:\n\n${rendered}\n\nRevise it according to the next instruction and return every file in full.`,
    });
  }

  messages.push({ role: "user", content: prompt });

  return messages;
}

/**
 * Whether a generated file set satisfies its kind's contract.
 *
 * Both kinds have exactly one required file, and it is what the prompt promises:
 * `index.html` for an app (the thing the sandboxed preview renders), `src/App.tsx`
 * for a website (the thing Vite compiles). Reporting a missing one at the API
 * boundary turns "the preview is blank" into a sentence that says why, and for a
 * website it is the difference between a build failure at packaging time — minutes
 * later, far from the cause — and an error where the user is looking.
 */
export function missingEntryPoint(files: PriorFile[], kind: ProjectKind): string | null {
  const expected = kind === "website" ? /(^|\/)src\/App\.(tsx|jsx)$/i : /(^|\/)index\.html?$/i;
  if (files.some((file) => expected.test(file.path))) return null;
  return kind === "website" ? "src/App.tsx" : "index.html";
}

/**
 * Pull the text delta out of one SSE payload, tolerating both the Chat
 * Completions shape and the Responses API shape — the gateway can be
 * configured for either.
 */
function extractDelta(payload: unknown): string {
  if (typeof payload !== "object" || payload === null) return "";
  const record = payload as Record<string, unknown>;

  const choices = record.choices;
  if (Array.isArray(choices) && choices.length > 0) {
    const choice = choices[0] as Record<string, unknown> | undefined;
    const carrier = (choice?.delta ?? choice?.message) as Record<string, unknown> | undefined;
    const content = carrier?.content;
    if (typeof content === "string") return content;
    if (Array.isArray(content)) {
      return content
        .map((part) => {
          const text = (part as Record<string, unknown> | undefined)?.text;
          return typeof text === "string" ? text : "";
        })
        .join("");
    }
  }

  if (typeof record.delta === "string") return record.delta;
  if (typeof record.output_text === "string") return record.output_text;

  return "";
}

function deltaFromSseLine(line: string): string {
  const trimmed = line.trim();
  if (!trimmed.startsWith("data:")) return "";

  const payload = trimmed.slice(5).trim();
  if (!payload || payload === "[DONE]") return "";

  try {
    return extractDelta(JSON.parse(payload));
  } catch {
    return "";
  }
}

/**
 * Convert an SSE byte stream into a plain-text stream of generated source, so
 * the browser can accumulate and parse code blocks as they arrive.
 */
export function sseToTextStream(source: ReadableStream<Uint8Array>): ReadableStream<Uint8Array> {
  const decoder = new TextDecoder();
  const encoder = new TextEncoder();
  let buffer = "";

  return source.pipeThrough(
    new TransformStream<Uint8Array, Uint8Array>({
      transform(chunk, controller) {
        buffer += decoder.decode(chunk, { stream: true });

        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";

        for (const line of lines) {
          const delta = deltaFromSseLine(line);
          if (delta) controller.enqueue(encoder.encode(delta));
        }
      },
      flush(controller) {
        buffer += decoder.decode();
        const delta = deltaFromSseLine(buffer);
        if (delta) controller.enqueue(encoder.encode(delta));
      },
    }),
  );
}
